# basic-reusable-workflows/.github/workflows/main.yml
name: Build Action

on:
  workflow_dispatch:

env:
  VERSION: '8.x'
  FIRST_NAME: 'Dude'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Calls Reusable
        uses: ./.github/actions/reusable
        with:
          dotnet-version: ${{ env.VERSION }}
          first-name: ${{ env.FIRST_NAME }}
