# basic-reusable-workflows/.github/workflows/test.yml
name: Basic Reusable Workflows Test Action

on:
  workflow_dispatch:
  push:
    paths:
      - "action.yml"
      - ".github/workflows/**"
      - "samples/**"

env:
  DOTNET-VERSION: "8.x"
  ACTIONS_RUNNER_DEBUG: true # Enable debug logging
  EXPECTED_COVERAGE: 50


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: "Check out code" # Only need for test as it needs to access the ./action.yml file
        uses: actions/checkout@v4

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.0.0'

      - name: Determine Version
        id: version-step
        uses: gittools/actions/gitversion/execute@v3.0.0
        with:
          useConfigFile: false

      - run: |
            echo "FullSemVer (env.fullSemVer)            : ${{ env.fullSemVer }}"
        name: Display GitVersion variables (without prefix)

      - run: |
            echo "FullSemVer (env.GitVersion_FullSemVer) : ${{ env.GitVersion_FullSemVer }}"
        name: Display GitVersion variables (with prefix)

      - run: |
            echo "FullSemVer (steps.version_step.outputs.fullSemVer)            : ${{ steps.version_step.outputs.fullSemVer }}"
        name: Display GitVersion outputs (step output without prefix)

      - run: |
            echo "FullSemVer (steps.version_step.outputs.GitVersion_FullSemVer) : ${{ steps.version_step.outputs.GitVersion_FullSemVer }}"
        name: Display GitVersion outputs (step output with prefix)



      - name: "Calls Reusable"
        id: reusable_build
        uses: ./
        with:
          DOTNET-VERSION: "${{ env.DOTNET-VERSION }}"
          SOLUTION-PATH: "./samples/DotNetConsoleSample/DotNetConsoleSample.sln"
          EXPECTED-COVERAGE: ${{ env.EXPECTED_COVERAGE }}
          SEMVER: ${{ env.GITVERSION }}

      - name: "Check reusable workflow exit code"
        if: ${{ steps.reusable_build.outcome != 'success' }}
        run: |
          echo "Reusable workflow failed with exit code ${{ steps.reusable_build.conclusion }}"
          exit 1
      
      - name: "Check code coverage"
        run: |
          echo "Code coverage is: ${{ steps.reusable_build.outputs.COVERAGE-PERCENTAGE }}"

