# basic-reusable-workflows/.github/workflows/test.yml
name: Test Action

on:
  workflow_dispatch:

env:
  VERSION: '8.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Calls Reusable
        uses: ./
        with:
          dotnet-version: ${{ env.VERSION }}
          solution-path: '**/DotNetConsoleSample.sln'
