# basic-reusable-workflows/.github/workflows/test.yml
name: Basic Reusable Workflows Test Action

on:
  workflow_dispatch:
  push:
    paths:
      - "action.yml"
      - ".github/workflows/**"
      - "samples/**"
    paths-ignore:
      - "README.md"

env:
  DOTNET-VERSION: "8.x"
  ACTIONS_RUNNER_DEBUG: true # Enable debug logging
  EXPECTED_COVERAGE: 50


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: "Check out code" # Only need for test as it needs to access the ./action.yml file
        uses: actions/checkout@v4

      - name: "Calls Reusable"
        id: reusable_build  # Assign an ID to the step to reference its outputs
        uses: ./
        with:
          DOTNET-VERSION: "${{ env.DOTNET-VERSION }}"
          SOLUTION-PATH: "./samples/DotNetConsoleSample/DotNetConsoleSample.sln"
          EXPECTED-COVERAGE: ${{ env.EXPECTED_COVERAGE }}
