# basic-reusable-workflows/.github/workflows/test.yml
name: Basic Reusable Workflows Test Action

on:
  workflow_dispatch:
  push:
    paths:
      - "action.yml"
      - ".github/workflows/**"
      - "samples/**"

env:
  DOTNET-VERSION: "8.x"
  ACTIONS_RUNNER_DEBUG: true # Enable debug logging
  EXPECTED_COVERAGE: 50


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: "Set up environment"
        run: |
         echo "PAT_TOKEN=${{ secrets.PAT_TOKEN }}" >> $GITHUB_ENV

      - name: "Validate PAT Token"
        if: ${{ env.PAT_TOKEN == '' }}
        run: |
          echo "Error: PAT_TOKEN is not set or is empty" && exit 1

      - name: "Continue if PAT_TOKEN is set"
        if: ${{ env.PAT_TOKEN != '' }}
        run: |
          echo "PAT_TOKEN is set"

      - name: "Check out code" # Only need for test as it needs to access the ./action.yml file
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.0.0'

      - name: Determine Version
        id: gitversion-execute
        uses: gittools/actions/gitversion/execute@v3.0.0
        with:
          useConfigFile: false

      - name: "Calls Reusable"
        id: reusable_build
        uses: ./
        with:
          DOTNET-VERSION: "${{ env.DOTNET-VERSION }}"
          SOLUTION-PATH: "./samples/DotNetConsoleSample/DotNetConsoleSample.sln"
          EXPECTED-COVERAGE: ${{ env.EXPECTED_COVERAGE }}
          SEMVER: ${{ steps.gitversion-execute.outputs.fullSemVer }}

      - name: "Check reusable workflow exit code"
        if: ${{ steps.reusable_build.outcome != 'success' }}
        run: |
          echo "Reusable workflow failed with exit code ${{ steps.reusable_build.conclusion }}"
          exit 1
      
      - name: "Check code coverage"
        run: |
          echo "Code coverage is: ${{ steps.reusable_build.outputs.COVERAGE-PERCENTAGE }}"

